const CARD_GAMES = [
  {
    name: 'California Speed',
    imgSrc: require('../../assets/californiaSpeed.jpg'),
    minAge: 7,
    howToPlayUrl:
      'https://www.itsalwaysautumn.com/play-california-speed-easy-card-game.html',
    requiresSpecialDeck: false,
    numPlayers: 2,
  },
  {
    name: 'Canasta',
    imgSrc: require('../../assets/canasta.png'),
    minAge: 12,
    howToPlayUrl: 'https://bicyclecards.com/how-to-play/canasta/',
    requiresSpecialDeck: false,
    numPlayers: 4,
  },
  {
    name: 'Egyptian Rat Slap',
    imgSrc: require('../../assets/ers.jpg'),
    minAge: 7,
    howToPlayUrl: 'https://bicyclecards.com/how-to-play/egyptian-rat-screw/',
    requiresSpecialDeck: false,
    numPlayers: '2+',
  },
  {
    name: 'FreeCell',
    imgSrc: require('../../assets/freeCell.jpg'),
    minAge: 12,
    howToPlayUrl: 'http://www.solitairecity.com/Help/FreeCell.shtml',
    requiresSpecialDeck: false,
    numPlayers: 1,
  },
  {
    name: 'Mau',
    imgSrc: require('../../assets/mau.jpeg'),
    minAge: 8,
    howToPlayUrl: 'https://en.wikipedia.org/wiki/Mao_(card_game)',
    requiresSpecialDeck: false,
    numPlayers: '3+',
  },
  {
    name: 'Nerts',
    imgSrc: require('../../assets/nerts.jpg'),
    minAge: 12,
    howToPlayUrl: 'https://bicyclecards.com/how-to-play/nerts/',
    requiresSpecialDeck: false,
    numPlayers: '2+',
  },
  {
    name: 'Phase 10',
    imgSrc: require('../../assets/phase10.jpg'),
    minAge: 7,
    howToPlayUrl: 'https://www.instructables.com/How-to-Play-Phase-10/',
    requiresSpecialDeck: true,
    numPlayers: '2+',
  },
  {
    name: 'Set',
    imgSrc: require('../../assets/set.jpg'),
    minAge: 8,
    howToPlayUrl: 'https://www.setgame.com/set/puzzle_rules',
    requiresSpecialDeck: true,
    numPlayers: '1+',
  },
  {
    name: 'SkipBo',
    imgSrc: require('../../assets/skipbo.jpg'),
    minAge: 8,
    howToPlayUrl: 'https://service.mattel.com/instruction_sheets/42050.pdf',
    requiresSpecialDeck: true,
    numPlayers: '2+',
  },
  {
    name: 'Sleeping Queens',
    imgSrc: require('../../assets/sleepingQueens.jpg'),
    minAge: 5,
    howToPlayUrl:
      'https://www.fgbradleys.com/rules/rules4/Sleeping%20Queens%20-%20rules.pdf',
    requiresSpecialDeck: true,
    numPlayers: '2+',
  },
  {
    name: 'Speed',
    imgSrc: require('../../assets/speed.jpg'),
    minAge: 8,
    howToPlayUrl: 'https://www.instructables.com/How-to-play-speed-card-game/',
    requiresSpecialDeck: false,
    numPlayers: '2',
  },
  {
    name: 'Spit',
    imgSrc: require('../../assets/spit.jpg'),
    minAge: 8,
    howToPlayUrl: 'https://bicyclecards.com/how-to-play/spit/',
    requiresSpecialDeck: false,
    numPlayers: '2',
  },
  {
    name: 'Solitaire',
    imgSrc: require('../../assets/solitaire.png'),
    minAge: 12,
    howToPlayUrl: 'https://bicyclecards.com/how-to-play/solitaire/',
    requiresSpecialDeck: false,
    numPlayers: '1',
  },
  {
    name: 'Spoons',
    imgSrc: require('../../assets/spoons.png'),
    minAge: 10,
    howToPlayUrl: 'https://bicyclecards.com/how-to-play/spoons/',
    requiresSpecialDeck: false,
    numPlayers: '3+',
  },
  {
    name: 'War',
    imgSrc: require('../../assets/war.jpg'),
    minAge: 5,
    howToPlayUrl: 'https://bicyclecards.com/how-to-play/war/',
    requiresSpecialDeck: false,
    numPlayers: '2+',
  },
];

export default CARD_GAMES;
